### ISSUE TITLE
Chapter titles should be send to Confessions

### ISSUE THREAD

**Issue by jackkinsella** [adamniedzielski/admission#1]
Right now it's just "Chapter {N}", but this isn't going to give us much SEO juice and I'm worried about usability.

Instead could you give each chapter preview a title (based on the filename of that chapter's markdown). Its slug should also match.

**Comment by adamniedzielski** [comment]
We cannot rely on the filename of a chapter's markdown file, because we will lose some information that way (for example which letters should be in capital, special characters and so on).

I suggest to modify the structure of `book_config.exs` file to include chapter name as well as filename. For example:

``` elixir
%{
  book_slug: "cmo",
  title: "My awesome book",
  author: "Adam Niedzielski",
  chapters: [
    [title: "This Is a Test", file_name: "this-is-a-test.md"]
  ]
}
```

What do you think?

**Comment by jackkinsella** [comment]
that works for me!

**Comment by adamniedzielski** [comment]
I did this change. :trumpet: :tada: 

Please mind that you have to update multiple things to get this to work:
- fetch and recompile admission
- change structure of the `book_config.exs` file
- fetch and migrate confessions

**Comment by jackkinsella** [comment]
Worked like a charm, thanks!
